import type { Metadata } from "next";
import Image from "next/image";

/**
 * INTERNAL REFERENCE PAGE. Not part of the marketing site.
 *
 * Catalogs every file in public/work-photos/ with a stable short ID, a
 * category, an honest read on whether it shows real evidence of work, and
 * exactly which pages currently use it. When asked to swap a photo, reference
 * the ID (e.g. "put DC-03 on the About page") rather than the filename, it is
 * shorter and does not change if the file gets renamed.
 *
 * Deliberately unindexed and unlinked: robots noindex/nofollow below, no link
 * from Navigation, Footer, or any other page, and no entry in app/sitemap.ts.
 * Reachable only if you know the URL.
 */
export const metadata: Metadata = {
  title: "Photo Library (Internal)",
  robots: { index: false, follow: false },
};

type Evidence = "Strong" | "Good" | "Moderate" | "Weak";

interface Photo {
  id: string;
  file: string;
  width: number;
  height: number;
  kb: number;
  evidence: Evidence;
  note: string;
  heroReady?: boolean;
  usedOn: string[]; // paths relative to app/, e.g. "deep-cleaning/page.tsx"
}

interface Category {
  key: string;
  title: string;
  goodFor: string;
  photos: Photo[];
}

const CATEGORIES: Category[] = [
  {
    key: "dc",
    title: "Deep Cleaning Evidence",
    goodFor:
      "Deep cleaning pages and anywhere the offer needs to look believable. These show a visible before/after moment, not just a tidy room.",
    photos: [
      {
        id: "DC-01",
        file: "oven-interior-deep-cleaning.jpg",
        width: 1200,
        height: 900,
        kb: 140,
        evidence: "Strong",
        note: "Open oven, bare blue enamel cavity, clean grates and knobs. The single best evidence photo in the library.",
        usedOn: ["deep-cleaning/page.tsx", "page.tsx", "pricing/page.tsx"],
      },
      {
        id: "DC-02",
        file: "cooktop-grates-deep-cleaning.jpg",
        width: 1200,
        height: 900,
        kb: 137,
        evidence: "Strong",
        note: "Gas cooktop, degreased burner grates, polished stainless trim.",
        usedOn: ["deep-cleaning/page.tsx"],
      },
      {
        id: "DC-03",
        file: "marble-bathroom-deep-cleaning.jpg",
        width: 760,
        height: 570,
        kb: 62,
        evidence: "Good",
        note: "Marble tiled bathroom, scrubbed tub surround, floor tile catching the light. Smaller file, only 760px wide, upscale with care.",
        usedOn: ["deep-cleaning/page.tsx", "page.tsx"],
      },
      {
        id: "DC-04",
        file: "shower-deep-clean-romeoville-il.jpg",
        width: 1920,
        height: 2560,
        kb: 499,
        evidence: "Good",
        note: "Glass shower door and chrome fixtures, streak-free. Portrait orientation, crops well to landscape from the top half.",
        usedOn: ["about/page.tsx", "airbnb-cleaning/page.tsx", "deep-clean-offer/page.tsx"],
      },
      {
        id: "DC-05",
        file: "walk-in-shower-glass-house-cleaning.jpg",
        width: 1200,
        height: 900,
        kb: 86,
        evidence: "Good",
        note: "Walk-in shower, streak-free glass doors, spotless tiled pan. Filename says house-cleaning but the content reads as deep-clean evidence.",
        usedOn: ["deep-cleaning/page.tsx", "page.tsx"],
      },
      {
        id: "DC-06",
        file: "shower-tile-cleaning-romeoville-il.jpg",
        width: 1920,
        height: 2560,
        kb: 539,
        evidence: "Moderate",
        note: "Tight crop on shower wall tile plus a chrome caddy and showerhead. Polished chrome is the only real evidence; mostly tile.",
        usedOn: [],
      },
      {
        id: "DC-07",
        file: "oven-interior-clean-empty.jpg",
        width: 1440,
        height: 1920,
        kb: 240,
        evidence: "Strong",
        note: "Empty stainless oven interior, spotless racks, no residue.",
        usedOn: [],
      },
      {
        id: "DC-08",
        file: "microwave-interior-spotless.jpg",
        width: 1920,
        height: 1440,
        kb: 238,
        evidence: "Strong",
        note: "Microwave interior close-up, glass tray and walls streak-free.",
        usedOn: [],
      },
      {
        id: "DC-09",
        file: "built-in-oven-microwave-combo-clean.jpg",
        width: 1440,
        height: 1920,
        kb: 230,
        evidence: "Strong",
        note: "Built-in wall oven and microwave combo, both interiors spotless.",
        usedOn: [],
      },
      {
        id: "DC-10",
        file: "stainless-sink-basin-spotless.jpg",
        width: 1440,
        height: 1920,
        kb: 101,
        evidence: "Good",
        note: "Empty stainless sink basin, dry and streak-free.",
        usedOn: [],
      },
      {
        id: "DC-11",
        file: "gas-cooktop-grates-closeup.jpg",
        width: 1920,
        height: 1440,
        kb: 254,
        evidence: "Strong",
        note: "Close-up on gas cooktop burners and grates, fully degreased.",
        usedOn: [],
      },
      {
        id: "DC-12",
        file: "microwave-interior-clean-2.jpg",
        width: 1920,
        height: 1440,
        kb: 154,
        evidence: "Good",
        note: "Second microwave interior shot, clean glass tray.",
        usedOn: [],
      },
      {
        id: "DC-13",
        file: "toilet-bowl-spotless-closeup.jpg",
        width: 1440,
        height: 1920,
        kb: 141,
        evidence: "Strong",
        note: "Extreme close-up inside a toilet bowl, rim and water spotless.",
        usedOn: [],
      },
      {
        id: "DC-14",
        file: "toilet-bowl-spotless-closeup-2.jpg",
        width: 1440,
        height: 1920,
        kb: 101,
        evidence: "Strong",
        note: "Second spotless toilet bowl close-up, different angle.",
        usedOn: [],
      },
      {
        id: "DC-15",
        file: "fridge-interior-shelves-spotless.jpg",
        width: 1920,
        height: 1440,
        kb: 235,
        evidence: "Good",
        note: "Open fridge, empty glass shelves wiped clean.",
        usedOn: [],
      },
      {
        id: "DC-16",
        file: "fridge-interior-shelves-spotless-2.jpg",
        width: 1440,
        height: 1920,
        kb: 253,
        evidence: "Good",
        note: "Second open fridge shot, clean empty shelves.",
        usedOn: [],
      },
      {
        id: "DC-17",
        file: "oven-interior-open-door-clean.jpg",
        width: 1440,
        height: 1920,
        kb: 258,
        evidence: "Strong",
        note: "Oven door open, spotless interior cavity.",
        usedOn: [],
      },
    ],
  },
  {
    key: "mo",
    title: "Move-In / Move-Out",
    goodFor:
      "Move-out pages and the deposit-back angle. Empty rooms with something visibly clean about them, not just empty.",
    photos: [
      {
        id: "MO-01",
        file: "empty-room-move-out-cleaning.jpg",
        width: 1200,
        height: 900,
        kb: 136,
        evidence: "Strong",
        note: "Empty carpeted room with strong diagonal vacuum lines. The best move-out evidence in the library.",
        usedOn: ["page.tsx", "pricing/page.tsx"],
      },
      {
        id: "MO-02",
        file: "apartment-move-out-cleaning-joliet-il.jpg",
        width: 1920,
        height: 2560,
        kb: 538,
        evidence: "Good",
        note: "Empty apartment, parquet floor with a strong window reflection. Portrait; the reused 4:3 crop is MO-03 below.",
        usedOn: [
          "apartment-cleaning/page.tsx",
          "move-out-cleaning/page.tsx",
          "move-out-cleaning-bolingbrook-il/page.tsx",
          "move-out-cleaning-joliet-il/page.tsx",
          "move-out-cleaning-lockport-il/page.tsx",
          "move-out-cleaning-minooka-il/page.tsx",
          "move-out-cleaning-new-lenox-il/page.tsx",
          "move-out-cleaning-plainfield-il/page.tsx",
          "move-out-cleaning-shorewood-il/page.tsx",
        ],
      },
      {
        id: "MO-03",
        file: "empty-apartment-parquet-move-out.jpg",
        width: 1200,
        height: 900,
        kb: 143,
        evidence: "Good",
        note: "Same apartment as MO-02, re-cropped to 4:3 and color-corrected. Not currently placed anywhere, available.",
        usedOn: [],
      },
      {
        id: "MO-04",
        file: "closet-move-out-cleaning.jpg",
        width: 760,
        height: 570,
        kb: 62,
        evidence: "Moderate",
        note: "Empty walk-in closet, bare white shelving, glossy oak floor with a real reflection. Only 760px wide.",
        usedOn: ["page.tsx"],
      },
      {
        id: "MO-05",
        file: "laundry-room-move-out-clean-romeoville-il.jpg",
        width: 1920,
        height: 2560,
        kb: 349,
        evidence: "Weak",
        note: "Washer and dryer, tidy laundry room. No visible evidence of cleaning, just an empty appliance shot.",
        usedOn: ["move-out-cleaning/page.tsx", "move-out-cleaning-romeoville-il/page.tsx"],
      },
      {
        id: "MO-06",
        file: "empty-bedroom-gray-carpet.jpg",
        width: 1440,
        height: 1920,
        kb: 223,
        evidence: "Moderate",
        note: "Empty bedroom, gray carpet, natural light.",
        usedOn: [],
      },
      {
        id: "MO-07",
        file: "empty-bedroom-gray-carpet-2.jpg",
        width: 1440,
        height: 1920,
        kb: 229,
        evidence: "Moderate",
        note: "Second empty bedroom, gray carpet.",
        usedOn: [],
      },
      {
        id: "MO-08",
        file: "empty-fridge-freezer-open.jpg",
        width: 1440,
        height: 1920,
        kb: 233,
        evidence: "Moderate",
        note: "Empty fridge and freezer, doors open, unit vacated.",
        usedOn: [],
      },
      {
        id: "MO-09",
        file: "empty-room-hardwood-1.jpg",
        width: 1440,
        height: 1920,
        kb: 173,
        evidence: "Moderate",
        note: "Empty room, hardwood floor.",
        usedOn: [],
      },
      {
        id: "MO-10",
        file: "empty-hallway-dark-carpet.jpg",
        width: 1440,
        height: 1920,
        kb: 372,
        evidence: "Moderate",
        note: "Empty hallway, dark carpet.",
        usedOn: [],
      },
      {
        id: "MO-11",
        file: "empty-hallway-closets-carpet.jpg",
        width: 1440,
        height: 1920,
        kb: 347,
        evidence: "Moderate",
        note: "Empty hallway with closet doors, dark carpet.",
        usedOn: [],
      },
      {
        id: "MO-12",
        file: "empty-room-dark-carpet-1.jpg",
        width: 1440,
        height: 1920,
        kb: 356,
        evidence: "Moderate",
        note: "Empty room, dark carpet.",
        usedOn: [],
      },
      {
        id: "MO-13",
        file: "empty-room-dark-carpet-2.jpg",
        width: 1440,
        height: 1920,
        kb: 356,
        evidence: "Moderate",
        note: "Second empty room, dark carpet.",
        usedOn: [],
      },
      {
        id: "MO-14",
        file: "empty-room-hardwood-ceiling-fan.jpg",
        width: 1440,
        height: 1920,
        kb: 219,
        evidence: "Moderate",
        note: "Empty room, hardwood floor, ceiling fan.",
        usedOn: [],
      },
      {
        id: "MO-15",
        file: "empty-living-room-hardwood-archway.jpg",
        width: 1440,
        height: 1920,
        kb: 211,
        evidence: "Moderate",
        note: "Empty living room, hardwood floor, arched doorway.",
        usedOn: [],
      },
      {
        id: "MO-16",
        file: "empty-room-hardwood-2.jpg",
        width: 1440,
        height: 1920,
        kb: 180,
        evidence: "Moderate",
        note: "Empty room, hardwood floor.",
        usedOn: [],
      },
      {
        id: "MO-17",
        file: "empty-room-hardwood-ceiling-fan-2.jpg",
        width: 1440,
        height: 1920,
        kb: 193,
        evidence: "Moderate",
        note: "Empty room, hardwood floor, ceiling fan.",
        usedOn: [],
      },
      {
        id: "MO-18",
        file: "empty-room-hardwood-3.jpg",
        width: 1440,
        height: 1920,
        kb: 176,
        evidence: "Moderate",
        note: "Empty room, hardwood floor.",
        usedOn: [],
      },
      {
        id: "MO-19",
        file: "empty-hallway-windows.jpg",
        width: 1440,
        height: 1920,
        kb: 192,
        evidence: "Moderate",
        note: "Empty hallway with windows.",
        usedOn: [],
      },
      {
        id: "MO-20",
        file: "empty-room-hardwood-ceiling-fan-3.jpg",
        width: 1440,
        height: 1920,
        kb: 179,
        evidence: "Moderate",
        note: "Empty room, hardwood floor, ceiling fan.",
        usedOn: [],
      },
      {
        id: "MO-21",
        file: "empty-room-hardwood-4.jpg",
        width: 1440,
        height: 1920,
        kb: 222,
        evidence: "Moderate",
        note: "Empty room, hardwood floor.",
        usedOn: [],
      },
      {
        id: "MO-22",
        file: "empty-room-dark-wood-sheer-curtain.jpg",
        width: 1440,
        height: 1920,
        kb: 227,
        evidence: "Moderate",
        note: "Empty room, dark wood floor, sheer curtains.",
        usedOn: [],
      },
      {
        id: "MO-23",
        file: "empty-room-dark-wood-1.jpg",
        width: 1440,
        height: 1920,
        kb: 234,
        evidence: "Moderate",
        note: "Empty room, dark wood floor.",
        usedOn: [],
      },
      {
        id: "MO-24",
        file: "empty-hallway-dark-wood.jpg",
        width: 1440,
        height: 1920,
        kb: 234,
        evidence: "Moderate",
        note: "Empty hallway, dark wood floor.",
        usedOn: [],
      },
      {
        id: "MO-25",
        file: "empty-room-wood-floor.jpg",
        width: 1440,
        height: 1920,
        kb: 198,
        evidence: "Moderate",
        note: "Empty room, wood floor.",
        usedOn: [],
      },
      {
        id: "MO-26",
        file: "empty-fridge-open-shelves.jpg",
        width: 1440,
        height: 1920,
        kb: 170,
        evidence: "Moderate",
        note: "Empty fridge, door open, bare shelves.",
        usedOn: [],
      },
      {
        id: "MO-27",
        file: "empty-room-hardwood-5.jpg",
        width: 1440,
        height: 1920,
        kb: 240,
        evidence: "Moderate",
        note: "Empty room, hardwood floor.",
        usedOn: [],
      },
      {
        id: "MO-28",
        file: "empty-room-hardwood-teal-wall.jpg",
        width: 1440,
        height: 1920,
        kb: 196,
        evidence: "Moderate",
        note: "Empty room, hardwood floor, dark teal accent wall.",
        usedOn: [],
      },
      {
        id: "MO-29",
        file: "empty-room-dark-hardwood.jpg",
        width: 1440,
        height: 1920,
        kb: 110,
        evidence: "Moderate",
        note: "Empty room, dark hardwood floor.",
        usedOn: [],
      },
      {
        id: "MO-30",
        file: "laundry-room-move-out-clean-2.jpg",
        width: 1440,
        height: 1920,
        kb: 190,
        evidence: "Weak",
        note: "Washer and dryer in a tidy laundry closet, second angle.",
        usedOn: [],
      },
      {
        id: "MO-31",
        file: "empty-room-carpet-ceiling-fan.jpg",
        width: 1440,
        height: 1920,
        kb: 262,
        evidence: "Moderate",
        note: "Empty room, carpet, ceiling fan.",
        usedOn: [],
      },
      {
        id: "MO-32",
        file: "empty-room-blue-walls-carpet.jpg",
        width: 1440,
        height: 1920,
        kb: 275,
        evidence: "Moderate",
        note: "Empty room, blue walls, carpet.",
        usedOn: [],
      },
      {
        id: "MO-33",
        file: "walk-in-closet-empty-shelving.jpg",
        width: 1440,
        height: 1920,
        kb: 130,
        evidence: "Moderate",
        note: "Empty walk-in closet, dark wood shelving.",
        usedOn: [],
      },
      {
        id: "MO-34",
        file: "empty-room-tray-ceiling-carpet.jpg",
        width: 1440,
        height: 1920,
        kb: 294,
        evidence: "Moderate",
        note: "Empty room, tray ceiling, carpet.",
        usedOn: [],
      },
      {
        id: "MO-35",
        file: "empty-room-dark-green-wall.jpg",
        width: 1440,
        height: 1920,
        kb: 226,
        evidence: "Moderate",
        note: "Empty room, dark green accent wall, hardwood floor.",
        usedOn: [],
      },
      {
        id: "MO-36",
        file: "empty-room-hardwood-6.jpg",
        width: 1440,
        height: 1920,
        kb: 205,
        evidence: "Moderate",
        note: "Empty room, hardwood floor.",
        usedOn: [],
      },
      {
        id: "MO-37",
        file: "empty-room-carpet-1.jpg",
        width: 1440,
        height: 1920,
        kb: 438,
        evidence: "Moderate",
        note: "Empty room, carpet.",
        usedOn: [],
      },
      {
        id: "MO-38",
        file: "empty-room-carpet-2.jpg",
        width: 1440,
        height: 1920,
        kb: 299,
        evidence: "Moderate",
        note: "Empty room, carpet.",
        usedOn: [],
      },
      {
        id: "MO-39",
        file: "empty-fridge-shelves-open.jpg",
        width: 1440,
        height: 1920,
        kb: 148,
        evidence: "Moderate",
        note: "Empty fridge, door open, glass shelves.",
        usedOn: [],
      },
      {
        id: "MO-40",
        file: "empty-fridge-shelves-open-2.jpg",
        width: 1440,
        height: 1920,
        kb: 131,
        evidence: "Moderate",
        note: "Second empty fridge, door open.",
        usedOn: [],
      },
      {
        id: "MO-41",
        file: "empty-room-hardwood-ceiling-fan-4.jpg",
        width: 1440,
        height: 1920,
        kb: 224,
        evidence: "Moderate",
        note: "Empty room, hardwood floor, ceiling fan.",
        usedOn: [],
      },
      {
        id: "MO-42",
        file: "empty-room-hardwood-7.jpg",
        width: 1440,
        height: 1920,
        kb: 232,
        evidence: "Moderate",
        note: "Empty room, hardwood floor.",
        usedOn: [],
      },
      {
        id: "MO-43",
        file: "empty-hallway-hardwood.jpg",
        width: 1440,
        height: 1920,
        kb: 255,
        evidence: "Moderate",
        note: "Empty hallway, hardwood floor.",
        usedOn: [],
      },
      {
        id: "MO-44",
        file: "empty-room-hardwood-fireplace.jpg",
        width: 1440,
        height: 1920,
        kb: 252,
        evidence: "Moderate",
        note: "Empty room, hardwood floor, fireplace.",
        usedOn: [],
      },
      {
        id: "MO-45",
        file: "empty-room-carpet-blue-walls.jpg",
        width: 1440,
        height: 1920,
        kb: 339,
        evidence: "Moderate",
        note: "Empty room, carpet, blue walls, windows.",
        usedOn: [],
      },
      {
        id: "MO-46",
        file: "closet-dark-shelving-empty.jpg",
        width: 1440,
        height: 1920,
        kb: 132,
        evidence: "Moderate",
        note: "Empty closet, dark red-toned shelving.",
        usedOn: [],
      },
    ],
  },
  {
    key: "ba",
    title: "Bathrooms, General",
    goodFor:
      "Standard cleaning, apartment pages, or filler where a bathroom photo is needed but the deep-clean angle is not the point. Honestly, mostly tidy rooms rather than evidence.",
    photos: [
      {
        id: "BA-01",
        file: "double-vanity-bathroom-clean-naperville-il.jpg",
        width: 1920,
        height: 2560,
        kb: 252,
        evidence: "Moderate",
        note: "Grey double vanity, quartz counter, large clean mirror. The most reused photo in the library, mostly as the old deep-cleaning city-page hero thumbnail.",
        usedOn: [
          "book/page.tsx",
          "deep-clean-offer/page.tsx",
          "deep-cleaning/burr-ridge/page.tsx",
          "deep-cleaning/downers-grove/page.tsx",
          "deep-cleaning/hinsdale/page.tsx",
          "deep-cleaning/oak-brook/page.tsx",
          "deep-cleaning-bolingbrook-il/page.tsx",
          "deep-cleaning-homer-glen-il/page.tsx",
          "deep-cleaning-joliet-il/page.tsx",
          "deep-cleaning-lemont-il/page.tsx",
          "deep-cleaning-lockport-il/page.tsx",
          "deep-cleaning-minooka-il/page.tsx",
          "deep-cleaning-naperville-il/page.tsx",
          "deep-cleaning-new-lenox-il/page.tsx",
          "deep-cleaning-plainfield-il/page.tsx",
          "deep-cleaning-romeoville-il/page.tsx",
          "deep-cleaning-shorewood-il/page.tsx",
          "deep-cleaning-westmont-il/page.tsx",
          "move-out-cleaning-burr-ridge-il/page.tsx",
          "move-out-cleaning-downers-grove-il/page.tsx",
          "move-out-cleaning-hinsdale-il/page.tsx",
          "move-out-cleaning-lemont-il/page.tsx",
          "move-out-cleaning-oak-brook-il/page.tsx",
          "move-out-cleaning-westmont-il/page.tsx",
        ],
      },
      {
        id: "BA-02",
        file: "apartment-bathroom-cleaning-naperville-il.jpg",
        width: 1920,
        height: 2560,
        kb: 502,
        evidence: "Weak",
        note: "Grey bathroom, bidet, white tile floor. Tidy, no visible cleaning evidence.",
        usedOn: [
          "apartment-cleaning/page.tsx",
          "move-out-cleaning-homer-glen-il/page.tsx",
          "move-out-cleaning-naperville-il/page.tsx",
          "standard-cleaning/page.tsx",
        ],
      },
      {
        id: "BA-03",
        file: "bathroom-shower-tub-deep-clean-plainfield-il.jpg",
        width: 1920,
        height: 2560,
        kb: 351,
        evidence: "Weak",
        note: "Shower and tub, beige tile. Tidy, no visible cleaning evidence despite the filename.",
        usedOn: ["move-out-cleaning/page.tsx"],
      },
      {
        id: "BA-04",
        file: "bathtub-shower-deep-clean-plainfield-il.jpg",
        width: 1920,
        height: 2560,
        kb: 270,
        evidence: "Weak",
        note: "White tub surround, green accent wall, flat lighting with no shine or reflection.",
        usedOn: ["book/page.tsx", "deep-clean-offer/page.tsx"],
      },
      {
        id: "BA-05",
        file: "double-sink-bathroom-deep-clean-plainfield-il.jpg",
        width: 1920,
        height: 2560,
        kb: 387,
        evidence: "Weak",
        note: "Green walls, white double-sink vanity. Tidy, no visible cleaning evidence.",
        usedOn: ["deep-clean-offer/page.tsx"],
      },
      {
        id: "BA-06",
        file: "empty-tub-shower-alcove.jpg",
        width: 1440,
        height: 1920,
        kb: 96,
        evidence: "Weak",
        note: "Empty tub and shower alcove, tidy, no strong evidence.",
        usedOn: [],
      },
      {
        id: "BA-07",
        file: "double-vanity-dark-cabinets-marble.jpg",
        width: 1440,
        height: 1920,
        kb: 220,
        evidence: "Weak",
        note: "Double sink vanity, dark cabinets, marble counter.",
        usedOn: [],
      },
      {
        id: "BA-08",
        file: "marble-bathroom-tub-mirror.jpg",
        width: 1440,
        height: 1920,
        kb: 177,
        evidence: "Weak",
        note: "Marble tile bathroom, tub, round mirror.",
        usedOn: [],
      },
      {
        id: "BA-09",
        file: "bathroom-shower-toilet-tidy.jpg",
        width: 1440,
        height: 1920,
        kb: 170,
        evidence: "Weak",
        note: "Shower and toilet, tidy, vacant unit.",
        usedOn: [],
      },
      {
        id: "BA-10",
        file: "double-vanity-hallway-view.jpg",
        width: 1440,
        height: 1920,
        kb: 168,
        evidence: "Weak",
        note: "Double vanity seen from hallway.",
        usedOn: [],
      },
      {
        id: "BA-11",
        file: "bathroom-arched-doorway-tub.jpg",
        width: 1440,
        height: 1920,
        kb: 246,
        evidence: "Weak",
        note: "Bathroom with arched doorway and tub.",
        usedOn: [],
      },
      {
        id: "BA-12",
        file: "bathroom-vanity-round-mirror.jpg",
        width: 1440,
        height: 1920,
        kb: 157,
        evidence: "Weak",
        note: "Bathroom vanity with round mirror.",
        usedOn: [],
      },
      {
        id: "BA-13",
        file: "shower-stall-glass-door.jpg",
        width: 1440,
        height: 1920,
        kb: 233,
        evidence: "Weak",
        note: "Glass shower stall, tidy.",
        usedOn: [],
      },
      {
        id: "BA-14",
        file: "bathroom-patterned-wall-tub-shower.jpg",
        width: 1440,
        height: 1920,
        kb: 247,
        evidence: "Weak",
        note: "Bathroom with patterned accent wall, tub and shower.",
        usedOn: [],
      },
      {
        id: "BA-15",
        file: "bathroom-hallway-glass-shower.jpg",
        width: 1440,
        height: 1920,
        kb: 180,
        evidence: "Weak",
        note: "Bathroom off a hallway, glass shower.",
        usedOn: [],
      },
      {
        id: "BA-16",
        file: "bathroom-long-vanity.jpg",
        width: 1440,
        height: 1920,
        kb: 141,
        evidence: "Weak",
        note: "Long bathroom vanity, single mirror.",
        usedOn: [],
      },
      {
        id: "BA-17",
        file: "small-bathroom-pedestal-sink.jpg",
        width: 1440,
        height: 1920,
        kb: 87,
        evidence: "Weak",
        note: "Small bathroom, pedestal sink.",
        usedOn: [],
      },
      {
        id: "BA-18",
        file: "bathroom-red-vanity-top-black-cabinets.jpg",
        width: 1440,
        height: 1920,
        kb: 220,
        evidence: "Weak",
        note: "Bathroom with red vanity top and black cabinets, distinctive retro style.",
        usedOn: [],
      },
      {
        id: "BA-19",
        file: "bathroom-tub-shower-tile.jpg",
        width: 1440,
        height: 1920,
        kb: 195,
        evidence: "Weak",
        note: "Bathroom tub and shower, tiled surround.",
        usedOn: [],
      },
      {
        id: "BA-20",
        file: "bathroom-vanity-mirror-1.jpg",
        width: 1440,
        height: 1920,
        kb: 148,
        evidence: "Weak",
        note: "Bathroom vanity and mirror.",
        usedOn: [],
      },
      {
        id: "BA-21",
        file: "bathroom-shower-glass-vanity.jpg",
        width: 1440,
        height: 1920,
        kb: 164,
        evidence: "Weak",
        note: "Bathroom with glass shower and vanity.",
        usedOn: [],
      },
      {
        id: "BA-22",
        file: "bathroom-vanity-tub-shower.jpg",
        width: 1440,
        height: 1920,
        kb: 131,
        evidence: "Weak",
        note: "Bathroom vanity, tub and shower.",
        usedOn: [],
      },
      {
        id: "BA-23",
        file: "shower-glass-door-closeup.jpg",
        width: 1440,
        height: 1920,
        kb: 245,
        evidence: "Moderate",
        note: "Close-up on a streak-free glass shower door.",
        usedOn: [],
      },
      {
        id: "BA-24",
        file: "shower-tile-wall-closeup.jpg",
        width: 1440,
        height: 1920,
        kb: 263,
        evidence: "Weak",
        note: "Close-up on tiled shower wall.",
        usedOn: [],
      },
      {
        id: "BA-25",
        file: "bathroom-tub-shower-toilet.jpg",
        width: 1440,
        height: 1920,
        kb: 165,
        evidence: "Weak",
        note: "Bathroom with tub, shower and toilet.",
        usedOn: [],
      },
      {
        id: "BA-26",
        file: "bathroom-double-vanity-white-1.jpg",
        width: 1440,
        height: 1920,
        kb: 140,
        evidence: "Weak",
        note: "White double vanity.",
        usedOn: [],
      },
      {
        id: "BA-27",
        file: "bathroom-double-vanity-white-2.jpg",
        width: 1440,
        height: 1920,
        kb: 145,
        evidence: "Weak",
        note: "Second white double vanity, different angle.",
        usedOn: [],
      },
      {
        id: "BA-28",
        file: "bathroom-shower-glass-toilet.jpg",
        width: 1440,
        height: 1920,
        kb: 180,
        evidence: "Weak",
        note: "Bathroom with glass shower and toilet.",
        usedOn: [],
      },
      {
        id: "BA-29",
        file: "bathroom-tub-shower-2.jpg",
        width: 1440,
        height: 1920,
        kb: 123,
        evidence: "Weak",
        note: "Bathroom tub and shower.",
        usedOn: [],
      },
      {
        id: "BA-30",
        file: "bathroom-vanity-dark-cabinets.jpg",
        width: 1440,
        height: 1920,
        kb: 179,
        evidence: "Weak",
        note: "Bathroom vanity, dark cabinets.",
        usedOn: [],
      },
      {
        id: "BA-31",
        file: "bathroom-vanity-dark-wood-floor.jpg",
        width: 1440,
        height: 1920,
        kb: 211,
        evidence: "Weak",
        note: "Bathroom vanity with dark wood floor.",
        usedOn: [],
      },
      {
        id: "BA-32",
        file: "bathroom-vanity-dark-granite.jpg",
        width: 1440,
        height: 1920,
        kb: 202,
        evidence: "Weak",
        note: "Bathroom vanity, dark granite counter.",
        usedOn: [],
      },
      {
        id: "BA-33",
        file: "bathroom-shower-window-tub.jpg",
        width: 1440,
        height: 1920,
        kb: 196,
        evidence: "Weak",
        note: "Bathroom shower near a window, tub.",
        usedOn: [],
      },
      {
        id: "BA-34",
        file: "bathroom-shower-vanity-mirror.jpg",
        width: 1440,
        height: 1920,
        kb: 240,
        evidence: "Weak",
        note: "Bathroom shower, vanity and mirror.",
        usedOn: [],
      },
      {
        id: "BA-35",
        file: "bathroom-vanity-tub-shower-2.jpg",
        width: 1440,
        height: 1920,
        kb: 119,
        evidence: "Weak",
        note: "Bathroom vanity, tub and shower.",
        usedOn: [],
      },
      {
        id: "BA-36",
        file: "bathroom-vanity-tub-shower-dark.jpg",
        width: 1440,
        height: 1920,
        kb: 125,
        evidence: "Weak",
        note: "Bathroom vanity, tub and shower, dark tones.",
        usedOn: [],
      },
      {
        id: "BA-37",
        file: "bathroom-vanity-dark-wood-floor-2.jpg",
        width: 1440,
        height: 1920,
        kb: 138,
        evidence: "Weak",
        note: "Bathroom vanity, dark wood floor.",
        usedOn: [],
      },
      {
        id: "BA-38",
        file: "shower-glass-sliding-door-1.jpg",
        width: 1440,
        height: 1920,
        kb: 153,
        evidence: "Weak",
        note: "Sliding glass shower door.",
        usedOn: [],
      },
      {
        id: "BA-39",
        file: "shower-glass-sliding-door-2.jpg",
        width: 1440,
        height: 1920,
        kb: 156,
        evidence: "Weak",
        note: "Second sliding glass shower door.",
        usedOn: [],
      },
      {
        id: "BA-40",
        file: "bathroom-vanity-mirror-2.jpg",
        width: 1440,
        height: 1920,
        kb: 170,
        evidence: "Weak",
        note: "Bathroom vanity and mirror.",
        usedOn: [],
      },
      {
        id: "BA-41",
        file: "bathroom-shower-glass-vanity-2.jpg",
        width: 1440,
        height: 1920,
        kb: 179,
        evidence: "Weak",
        note: "Bathroom with glass shower and vanity.",
        usedOn: [],
      },
      {
        id: "BA-42",
        file: "bathroom-shower-curtain-vanity.jpg",
        width: 1440,
        height: 1920,
        kb: 164,
        evidence: "Weak",
        note: "Bathroom with shower curtain and vanity.",
        usedOn: [],
      },
      {
        id: "BA-43",
        file: "bathroom-vanity-round-mirror-shower.jpg",
        width: 1440,
        height: 1920,
        kb: 149,
        evidence: "Weak",
        note: "Bathroom vanity, round mirror, shower visible.",
        usedOn: [],
      },
      {
        id: "BA-44",
        file: "bathroom-double-vanity-round-mirrors.jpg",
        width: 1440,
        height: 1920,
        kb: 220,
        evidence: "Weak",
        note: "Double vanity, two round mirrors.",
        usedOn: [],
      },
      {
        id: "BA-45",
        file: "shower-glass-tiled-closeup.jpg",
        width: 1440,
        height: 1920,
        kb: 248,
        evidence: "Moderate",
        note: "Close-up on tiled glass shower.",
        usedOn: [],
      },
      {
        id: "BA-46",
        file: "glass-shower-door-closeup-2.jpg",
        width: 1440,
        height: 1920,
        kb: 269,
        evidence: "Moderate",
        note: "Close-up on a glass shower door.",
        usedOn: [],
      },
      {
        id: "BA-47",
        file: "bathroom-window-shower-glass.jpg",
        width: 1440,
        height: 1920,
        kb: 230,
        evidence: "Weak",
        note: "Bathroom with window and glass shower.",
        usedOn: [],
      },
      {
        id: "BA-48",
        file: "bathroom-glass-shower-tub-granite.jpg",
        width: 1440,
        height: 1920,
        kb: 227,
        evidence: "Weak",
        note: "Bathroom with glass shower, tub, granite counter.",
        usedOn: [],
      },
      {
        id: "BA-49",
        file: "bathroom-marble-shower-toilet.jpg",
        width: 1440,
        height: 1920,
        kb: 212,
        evidence: "Weak",
        note: "Bathroom with marble shower surround and toilet.",
        usedOn: [],
      },
      {
        id: "BA-50",
        file: "bathroom-window-tub.jpg",
        width: 1440,
        height: 1920,
        kb: 174,
        evidence: "Weak",
        note: "Bathroom with window above the tub.",
        usedOn: [],
      },
      {
        id: "BA-51",
        file: "bathroom-vanity-long-mirror.jpg",
        width: 1440,
        height: 1920,
        kb: 174,
        evidence: "Weak",
        note: "Bathroom vanity with a long mirror.",
        usedOn: [],
      },
      {
        id: "BA-52",
        file: "bathroom-fixture-reflection-closeup.jpg",
        width: 1920,
        height: 1440,
        kb: 294,
        evidence: "Weak",
        note: "Reflective close-up on chrome bathroom fixtures, abstract composition, low standalone value.",
        usedOn: [],
      },
      {
        id: "BA-53",
        file: "bathroom-double-vanity-marble-1.jpg",
        width: 1440,
        height: 1920,
        kb: 248,
        evidence: "Weak",
        note: "Double vanity, marble counter.",
        usedOn: [],
      },
      {
        id: "BA-54",
        file: "bathroom-vanity-marble-window.jpg",
        width: 1440,
        height: 1920,
        kb: 191,
        evidence: "Weak",
        note: "Bathroom vanity, marble counter, window.",
        usedOn: [],
      },
      {
        id: "BA-55",
        file: "bathroom-vanity-shower-glass.jpg",
        width: 1440,
        height: 1920,
        kb: 220,
        evidence: "Weak",
        note: "Bathroom vanity with glass shower.",
        usedOn: [],
      },
      {
        id: "BA-56",
        file: "bathroom-shower-glass-tile.jpg",
        width: 1440,
        height: 1920,
        kb: 210,
        evidence: "Weak",
        note: "Bathroom shower, glass door, tile surround.",
        usedOn: [],
      },
      {
        id: "BA-57",
        file: "bathroom-vanity-tub-oval-mirrors.jpg",
        width: 1440,
        height: 1920,
        kb: 209,
        evidence: "Weak",
        note: "Bathroom vanity and tub, oval mirrors.",
        usedOn: [],
      },
      {
        id: "BA-58",
        file: "bathroom-shower-window-vanity.jpg",
        width: 1440,
        height: 1920,
        kb: 181,
        evidence: "Weak",
        note: "Bathroom shower near window, vanity.",
        usedOn: [],
      },
    ],
  },
  {
    key: "kl",
    title: "Kitchens & Living Areas",
    goodFor:
      "Standard/house cleaning pages, hero backgrounds, and general context shots. Mostly staged or tidy rather than evidence-driven; use these to set a scene, not to prove a scrub.",
    photos: [
      {
        id: "KL-01",
        file: "living-room-hardwood-floors-plainfield-il.jpg",
        width: 1920,
        height: 2560,
        kb: 470,
        evidence: "Good",
        note: "Empty living room, plank floor with strong specular highlights, large plain wall on the left. The most versatile wide-crop source in the library.",
        heroReady: true,
        usedOn: ["about/page.tsx", "airbnb-cleaning/page.tsx", "book/page.tsx", "deep-clean-offer/page.tsx", "standard-cleaning/page.tsx"],
      },
      {
        id: "KL-02",
        file: "living-room-house-cleaning.jpg",
        width: 1200,
        height: 900,
        kb: 132,
        evidence: "Good",
        note: "Same room as KL-01, re-cropped to 4:3 and color-corrected. Not currently placed anywhere, available.",
        usedOn: [],
      },
      {
        id: "KL-03",
        file: "hero-kitchen-home.jpg",
        width: 1200,
        height: 675,
        kb: 85,
        evidence: "Moderate",
        note: "Wide kitchen crop, white cabinets, stainless appliances, orange barstools. Current homepage hero background.",
        heroReady: true,
        usedOn: ["page.tsx"],
      },
      {
        id: "KL-04",
        file: "google-post-image-cleaning-service-1.jpg",
        width: 940,
        height: 788,
        kb: 106,
        evidence: "Moderate",
        note: "Bright kitchen, granite island, dark wood cabinets. Originally a Google Business post image, heavily reused across the deep cleaning city pages.",
        usedOn: [
          "about/page.tsx",
          "deep-cleaning/burr-ridge/page.tsx",
          "deep-cleaning/downers-grove/page.tsx",
          "deep-cleaning/hinsdale/page.tsx",
          "deep-cleaning/oak-brook/page.tsx",
          "deep-cleaning-bolingbrook-il/page.tsx",
          "deep-cleaning-homer-glen-il/page.tsx",
          "deep-cleaning-joliet-il/page.tsx",
          "deep-cleaning-lemont-il/page.tsx",
          "deep-cleaning-lockport-il/page.tsx",
          "deep-cleaning-minooka-il/page.tsx",
          "deep-cleaning-naperville-il/page.tsx",
          "deep-cleaning-new-lenox-il/page.tsx",
          "deep-cleaning-plainfield-il/page.tsx",
          "deep-cleaning-romeoville-il/page.tsx",
          "deep-cleaning-shorewood-il/page.tsx",
          "deep-cleaning-westmont-il/page.tsx",
          "page.tsx",
        ],
      },
      {
        id: "KL-05",
        file: "kitchen-standard-cleaning.jpg",
        width: 1200,
        height: 900,
        kb: 103,
        evidence: "Weak",
        note: "Staged kitchen, white cabinets, orange stools. Reads as a real-estate listing photo, not proof of cleaning; a home that was never dirty looks the same.",
        usedOn: ["pricing/page.tsx"],
      },
      {
        id: "KL-06",
        file: "kitchen-dark-cabinets-stainless-1.jpg",
        width: 1920,
        height: 1440,
        kb: 174,
        evidence: "Weak",
        note: "Kitchen, dark cabinets, stainless appliances.",
        usedOn: [],
      },
      {
        id: "KL-07",
        file: "kitchen-range-cabinets-closeup.jpg",
        width: 1440,
        height: 1920,
        kb: 194,
        evidence: "Weak",
        note: "Close-up on kitchen range and cabinets.",
        usedOn: [],
      },
      {
        id: "KL-08",
        file: "kitchen-dark-cabinets-hardwood.jpg",
        width: 1440,
        height: 1920,
        kb: 264,
        evidence: "Weak",
        note: "Kitchen, dark cabinets, hardwood floor.",
        usedOn: [],
      },
      {
        id: "KL-09",
        file: "kitchen-dark-cabinets-island.jpg",
        width: 1440,
        height: 1920,
        kb: 296,
        evidence: "Weak",
        note: "Kitchen with island, dark cabinets.",
        usedOn: [],
      },
      {
        id: "KL-10",
        file: "dining-checkered-floor-red-chairs.jpg",
        width: 1440,
        height: 1920,
        kb: 284,
        evidence: "Weak",
        note: "Retro dining nook, checkered floor, red chairs. Distinctive, not neutral enough for most pages.",
        usedOn: [],
      },
      {
        id: "KL-11",
        file: "retro-red-kitchen-checkered-floor.jpg",
        width: 1440,
        height: 1920,
        kb: 215,
        evidence: "Weak",
        note: "Retro red kitchen with checkered floor, same unit as KL-10.",
        usedOn: [],
      },
      {
        id: "KL-12",
        file: "living-room-leather-couch-furnished.jpg",
        width: 1440,
        height: 1920,
        kb: 336,
        evidence: "Weak",
        note: "Furnished living room, leather couch.",
        usedOn: [],
      },
      {
        id: "KL-13",
        file: "living-room-tv-stand-furnished.jpg",
        width: 1440,
        height: 1920,
        kb: 277,
        evidence: "Weak",
        note: "Furnished living room, TV stand.",
        usedOn: [],
      },
      {
        id: "KL-14",
        file: "kitchen-white-cabinets-island-1.jpg",
        width: 1440,
        height: 1920,
        kb: 205,
        evidence: "Weak",
        note: "Kitchen, white cabinets, island.",
        usedOn: [],
      },
      {
        id: "KL-15",
        file: "stainless-fridge-exterior.jpg",
        width: 1440,
        height: 1920,
        kb: 144,
        evidence: "Weak",
        note: "Stainless fridge, exterior view.",
        usedOn: [],
      },
      {
        id: "KL-16",
        file: "kitchen-white-cabinets-wide-1.jpg",
        width: 1920,
        height: 1440,
        kb: 159,
        evidence: "Weak",
        note: "Wide kitchen shot, white cabinets.",
        usedOn: [],
      },
      {
        id: "KL-17",
        file: "kitchen-white-cabinets-wide-2.jpg",
        width: 1440,
        height: 1920,
        kb: 178,
        evidence: "Weak",
        note: "Second wide kitchen shot, white cabinets, stainless.",
        usedOn: [],
      },
      {
        id: "KL-18",
        file: "living-kitchen-combo-hardwood.jpg",
        width: 1440,
        height: 1920,
        kb: 286,
        evidence: "Weak",
        note: "Open living and kitchen combo, hardwood floor.",
        usedOn: [],
      },
      {
        id: "KL-19",
        file: "living-room-hardwood-beams-windows.jpg",
        width: 1440,
        height: 1920,
        kb: 313,
        evidence: "Moderate",
        note: "Living room, exposed beams, hardwood floor, bright windows.",
        usedOn: [],
      },
      {
        id: "KL-20",
        file: "kitchen-wood-cabinets-island.jpg",
        width: 1440,
        height: 1920,
        kb: 301,
        evidence: "Weak",
        note: "Kitchen, wood cabinets, island.",
        usedOn: [],
      },
      {
        id: "KL-21",
        file: "kitchen-stainless-fridge-dark-cabinets.jpg",
        width: 1440,
        height: 1920,
        kb: 267,
        evidence: "Weak",
        note: "Kitchen, stainless fridge, dark cabinets.",
        usedOn: [],
      },
      {
        id: "KL-22",
        file: "kitchen-stainless-double-fridge.jpg",
        width: 1440,
        height: 1920,
        kb: 265,
        evidence: "Weak",
        note: "Kitchen, stainless double-door fridge.",
        usedOn: [],
      },
      {
        id: "KL-23",
        file: "kitchen-island-pendant-lights.jpg",
        width: 1440,
        height: 1920,
        kb: 209,
        evidence: "Weak",
        note: "Kitchen island under pendant lights.",
        usedOn: [],
      },
      {
        id: "KL-24",
        file: "kitchen-island-marble-long.jpg",
        width: 1440,
        height: 1920,
        kb: 166,
        evidence: "Weak",
        note: "Long marble kitchen island.",
        usedOn: [],
      },
      {
        id: "KL-25",
        file: "sunroom-hardwood-french-doors.jpg",
        width: 1440,
        height: 1920,
        kb: 367,
        evidence: "Moderate",
        note: "Sunroom with hardwood floor, French doors to the yard.",
        usedOn: [],
      },
      {
        id: "KL-26",
        file: "kitchen-living-open-concept-island.jpg",
        width: 1440,
        height: 1920,
        kb: 208,
        evidence: "Weak",
        note: "Open concept kitchen and living area, island.",
        usedOn: [],
      },
      {
        id: "KL-27",
        file: "kitchen-white-island-wood.jpg",
        width: 1440,
        height: 1920,
        kb: 171,
        evidence: "Weak",
        note: "Kitchen, white island, wood cabinets.",
        usedOn: [],
      },
      {
        id: "KL-28",
        file: "home-office-furnished.jpg",
        width: 1440,
        height: 1920,
        kb: 446,
        evidence: "Weak",
        note: "Furnished home office, wall decor.",
        usedOn: [],
      },
      {
        id: "KL-29",
        file: "dining-room-table-chairs.jpg",
        width: 1440,
        height: 1920,
        kb: 301,
        evidence: "Weak",
        note: "Dining room, table and chairs.",
        usedOn: [],
      },
      {
        id: "KL-30",
        file: "kitchen-wood-cabinets-stainless.jpg",
        width: 1440,
        height: 1920,
        kb: 286,
        evidence: "Weak",
        note: "Kitchen, wood cabinets, stainless appliances.",
        usedOn: [],
      },
      {
        id: "KL-31",
        file: "living-room-leather-couch-fireplace.jpg",
        width: 1440,
        height: 1920,
        kb: 252,
        evidence: "Weak",
        note: "Living room, leather couch, fireplace.",
        usedOn: [],
      },
      {
        id: "KL-32",
        file: "living-room-fireplace-hardwood.jpg",
        width: 1440,
        height: 1920,
        kb: 312,
        evidence: "Weak",
        note: "Living room, fireplace, hardwood floor.",
        usedOn: [],
      },
      {
        id: "KL-33",
        file: "kitchen-wood-cabinets-stainless-island.jpg",
        width: 1440,
        height: 1920,
        kb: 277,
        evidence: "Weak",
        note: "Kitchen, wood cabinets, stainless island.",
        usedOn: [],
      },
      {
        id: "KL-34",
        file: "kitchen-white-cabinets-stainless-2.jpg",
        width: 1920,
        height: 1440,
        kb: 288,
        evidence: "Weak",
        note: "Kitchen, white cabinets, stainless appliances.",
        usedOn: [],
      },
      {
        id: "KL-35",
        file: "kitchen-dining-open-hardwood.jpg",
        width: 1440,
        height: 1920,
        kb: 237,
        evidence: "Weak",
        note: "Open kitchen and dining area, hardwood floor.",
        usedOn: [],
      },
      {
        id: "KL-36",
        file: "kitchen-granite-island-stainless-1.jpg",
        width: 1440,
        height: 1920,
        kb: 241,
        evidence: "Weak",
        note: "Kitchen, granite island, stainless appliances.",
        usedOn: [],
      },
      {
        id: "KL-37",
        file: "kitchen-white-cabinets-black-counter.jpg",
        width: 1440,
        height: 1920,
        kb: 192,
        evidence: "Weak",
        note: "Kitchen, white cabinets, black counter.",
        usedOn: [],
      },
      {
        id: "KL-38",
        file: "kitchen-granite-island-stainless-2.jpg",
        width: 1440,
        height: 1920,
        kb: 229,
        evidence: "Weak",
        note: "Second kitchen, granite island, stainless appliances.",
        usedOn: [],
      },
      {
        id: "KL-39",
        file: "kitchen-wide-marble-floor.jpg",
        width: 1440,
        height: 1920,
        kb: 251,
        evidence: "Weak",
        note: "Wide kitchen shot, marble floor.",
        usedOn: [],
      },
      {
        id: "KL-40",
        file: "kitchen-white-island-pendant.jpg",
        width: 1440,
        height: 1920,
        kb: 223,
        evidence: "Weak",
        note: "Kitchen, white island, pendant lighting.",
        usedOn: [],
      },
      {
        id: "KL-41",
        file: "kitchen-stainless-fridge-range.jpg",
        width: 1440,
        height: 1920,
        kb: 208,
        evidence: "Weak",
        note: "Kitchen, stainless fridge and range.",
        usedOn: [],
      },
    ],
  },
  {
    key: "br",
    title: "Bedrooms",
    goodFor: "Airbnb turnover, standard cleaning, or move-out context involving a furnished room.",
    photos: [
      {
        id: "BR-01",
        file: "bedroom-cleaning-service-bolingbrook-il.jpg",
        width: 1920,
        height: 2560,
        kb: 450,
        evidence: "Moderate",
        note: "Empty bedroom, vinyl plank floor with some reflection, mirrored closet doors.",
        usedOn: ["apartment-cleaning/page.tsx", "book/page.tsx", "standard-cleaning/page.tsx"],
      },
      {
        id: "BR-02",
        file: "master-bedroom-airbnb-cleaning-bolingbrook-il.jpg",
        width: 1920,
        height: 2560,
        kb: 613,
        evidence: "Weak",
        note: "Staged bedroom, orange throw blanket, city balcony view. No cleaning evidence, but the staged look fits an Airbnb turnover context specifically.",
        usedOn: ["airbnb-cleaning/page.tsx", "deep-clean-offer/page.tsx"],
      },
      {
        id: "BR-03",
        file: "bedroom-furnished-natural-light.jpg",
        width: 1440,
        height: 1920,
        kb: 342,
        evidence: "Weak",
        note: "Furnished bedroom, natural light.",
        usedOn: [],
      },
    ],
  },
  {
    key: "tm",
    title: "Team / People at Work",
    goodFor:
      "About page, trust sections, anywhere the story is 'a real person does this work,' not just the result.",
    photos: [
      {
        id: "TM-01",
        file: "team-member-vacuuming.jpg",
        width: 1200,
        height: 900,
        kb: 93,
        evidence: "Strong",
        note: "Team member walking through a home wearing a backpack vacuum, mid-job. Native 16:9 before cropping.",
        heroReady: true,
        usedOn: ["page.tsx"],
      },
      {
        id: "TM-02",
        file: "google-post-image-cleaning-service-25.jpg",
        width: 940,
        height: 788,
        kb: 82,
        evidence: "Strong",
        note: "Team member reaching up to dust a light fixture, cloth in hand, mid-job.",
        usedOn: ["about/page.tsx", "deep-cleaning/page.tsx"],
      },
    ],
  },
  {
    key: "he",
    title: "Wide / Unplaced Hero Source",
    goodFor: "Any full-bleed hero that needs a wide, uncluttered background.",
    photos: [
      {
        id: "HE-01",
        file: "hero-home.jpg",
        width: 1920,
        height: 1080,
        kb: 215,
        evidence: "Moderate",
        note: "Wide crop of the Plainfield living room (KL-01/KL-02's source room), 16:9. Was the homepage hero before it switched to the kitchen; not used anywhere now.",
        heroReady: true,
        usedOn: [],
      },
    ],
  },
];

const EVIDENCE_STYLE: Record<Evidence, string> = {
  Strong: "bg-green-100 text-green-700",
  Good: "bg-blue-100 text-blue-700",
  Moderate: "bg-amber-100 text-amber-700",
  Weak: "bg-gray-100 text-gray-500",
};

// Lower ranks first, so sorting by this puts the strongest evidence at the
// top of a grid instead of relying on ID order (which is just import order).
const EVIDENCE_RANK: Record<Evidence, number> = {
  Strong: 0,
  Good: 1,
  Moderate: 2,
  Weak: 3,
};

function byEvidenceDesc(a: Photo, b: Photo): number {
  return EVIDENCE_RANK[a.evidence] - EVIDENCE_RANK[b.evidence];
}

function routeLabel(appPath: string): string {
  if (appPath === "page.tsx") return "/ (Homepage)";
  return "/" + appPath.replace(/\/page\.tsx$/, "");
}

function PhotoCard({ photo, categoryLabel }: { photo: Photo; categoryLabel?: string }) {
  return (
    <div className="bg-white rounded-xl border border-gray-200 overflow-hidden">
      <div className="relative bg-gray-100">
        <Image
          src={`/work-photos/${photo.file}`}
          alt={photo.note}
          width={photo.width}
          height={photo.height}
          sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
          className="w-full h-auto"
        />
        <span className="absolute top-2 left-2 bg-gray-900 text-white text-xs font-bold px-2 py-1 rounded">
          {photo.id}
        </span>
        <span
          className={`absolute top-2 right-2 text-xs font-bold px-2 py-1 rounded ${EVIDENCE_STYLE[photo.evidence]}`}
        >
          {photo.evidence}
        </span>
      </div>
      <div className="p-4">
        {categoryLabel && (
          <p className="text-xs font-semibold text-gray-400 uppercase tracking-wide mb-1">{categoryLabel}</p>
        )}
        <p className="font-mono text-xs text-gray-500 mb-2 break-all">{photo.file}</p>
        <p className="text-xs text-gray-400 mb-2">
          {photo.width}x{photo.height} &middot; {photo.kb}K
          {photo.heroReady && (
            <span className="ml-2 text-blue-600 font-semibold">&middot; hero-ready (wide)</span>
          )}
        </p>
        <p className="text-sm text-gray-700 leading-relaxed mb-3">{photo.note}</p>
        {photo.usedOn.length === 0 ? (
          <p className="text-xs font-semibold text-amber-600">Not currently used, available</p>
        ) : (
          <details className="text-xs">
            <summary className="cursor-pointer font-semibold text-gray-600">
              Used on {photo.usedOn.length} page{photo.usedOn.length === 1 ? "" : "s"}
            </summary>
            <ul className="mt-2 space-y-0.5 text-gray-500">
              {photo.usedOn.map((p) => (
                <li key={p} className="font-mono break-all">{routeLabel(p)}</li>
              ))}
            </ul>
          </details>
        )}
      </div>
    </div>
  );
}

export default function PhotoLibraryPage() {
  const total = CATEGORIES.reduce((sum, c) => sum + c.photos.length, 0);
  const unused = CATEGORIES.reduce((sum, c) => sum + c.photos.filter((p) => p.usedOn.length === 0).length, 0);

  const strongPhotos = CATEGORIES.flatMap((cat) =>
    cat.photos
      .filter((p) => p.evidence === "Strong")
      .map((p) => ({ photo: p, categoryLabel: cat.title }))
  );

  return (
    <div className="bg-gray-50 min-h-screen py-12 px-4">
      <div className="max-w-7xl mx-auto">
        <div className="mb-10">
          <p className="text-xs font-bold text-amber-600 uppercase tracking-widest mb-2">
            Internal only, not indexed, not linked from the site
          </p>
          <h1 className="text-3xl font-bold text-gray-900 mb-3">Photo Library</h1>
          <p className="text-gray-600 max-w-3xl leading-relaxed">
            Every file in <code className="font-mono text-sm bg-gray-200 px-1.5 py-0.5 rounded">public/work-photos/</code>,
            {" "}{total} total, {unused} not currently used anywhere. Each has a stable ID like{" "}
            <code className="font-mono text-sm bg-gray-200 px-1.5 py-0.5 rounded">DC-01</code>. To swap a photo later,
            reference the ID rather than the filename, for example &ldquo;put MO-03 on the Joliet move-out page.&rdquo;
          </p>
          <p className="text-gray-500 text-sm mt-3 max-w-3xl leading-relaxed">
            The evidence rating is an honest read on whether the photo shows visible proof of cleaning (vacuum
            lines, a scrubbed cavity, streak-free glass) versus just a tidy room. A tidy room that was never dirty
            looks identical to one that was just cleaned, so Weak-rated photos are weaker persuasion even though
            nothing is wrong with them.
          </p>
        </div>

        <div className="mb-14">
          <h2 className="text-xl font-bold text-gray-900 mb-1">Strongest Evidence (All Categories)</h2>
          <p className="text-sm text-gray-500 mb-5 max-w-3xl">
            Every Strong-rated photo across the whole library, pulled to the top so the best proof shots are never
            buried in a category grid. Same photos also appear below in their own category.
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
            {strongPhotos.map(({ photo, categoryLabel }) => (
              <PhotoCard key={`strong-${photo.id}`} photo={photo} categoryLabel={categoryLabel} />
            ))}
          </div>
        </div>

        {CATEGORIES.map((cat) => (
          <div key={cat.key} className="mb-12">
            <h2 className="text-xl font-bold text-gray-900 mb-1">{cat.title}</h2>
            <p className="text-sm text-gray-500 mb-5 max-w-3xl">{cat.goodFor}</p>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
              {[...cat.photos].sort(byEvidenceDesc).map((photo) => (
                <PhotoCard key={photo.id} photo={photo} />
              ))}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
